### ISSUE TITLE
Generated documents can be downloaded without authentication from an easily guessable URL

### ISSUE THREAD

**Issue by sur5r** [byro/byro-gemeinnuetzigkeit#5]
Subject says it all.

I'm not sure whether this is intentional or not.

- If the public download is intentional, a random path component could be added.
- If it's not intentional, it would be nice if the document gets added to the existing document management in byro, so it gets a `/documents/` URL.

**Comment by rixx** [comment]
I have no memory of the original intention and haven't used byro in five years, I'm afraid to say. Either solution sounds good to me, and I can add in one rn.

The bigger trouble is that this won't help for already-generated documents; you'd have to change them in the db and on disc.

**Comment by rixx** [comment]
(Not tested, looked straightforward, yell at me if it breaks.)
